//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rafeek.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rafeek.Application.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية الترم الأكاديمي مطلوب.
        /// </summary>
        public static string AcademicTermEndDateRequired {
            get {
                return ResourceManager.GetString("AcademicTermEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف السنة الدراسية مطلوب.
        /// </summary>
        public static string AcademicTermIdRequired {
            get {
                return ResourceManager.GetString("AcademicTermIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الترم الأكاديمي مطلوب.
        /// </summary>
        public static string AcademicTermNameRequired {
            get {
                return ResourceManager.GetString("AcademicTermNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترم الأكاديمي غير موجود.
        /// </summary>
        public static string AcademicTermNotFound {
            get {
                return ResourceManager.GetString("AcademicTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية الترم الأكاديمي مطلوب.
        /// </summary>
        public static string AcademicTermStartDateRequired {
            get {
                return ResourceManager.GetString("AcademicTermStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم السنة الأكاديمية مطلوب.
        /// </summary>
        public static string AcademicYearNameRequired {
            get {
                return ResourceManager.GetString("AcademicYearNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الدراسية غير موجودة في النظام.
        /// </summary>
        public static string AcademicYearNotFound {
            get {
                return ResourceManager.GetString("AcademicYearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قبول الطلب بنجاح.
        /// </summary>
        public static string AcceptedActionResultMessage {
            get {
                return ResourceManager.GetString("AcceptedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت الإضافة.
        /// </summary>
        public static string AddedFailed {
            get {
                return ResourceManager.GetString("AddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الأدوار الإضافية يجب أن تكون صحيحة.
        /// </summary>
        public static string AdditionalRolesInvalid {
            get {
                return ResourceManager.GetString("AdditionalRolesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المرشد الأكاديمي غير صحيح.
        /// </summary>
        public static string AdvisorIdNotFound {
            get {
                return ResourceManager.GetString("AdvisorIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المرشد الأكاديمي مطلوب.
        /// </summary>
        public static string AdvisorIdRequired {
            get {
                return ResourceManager.GetString("AdvisorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف التكليف مطلوب.
        /// </summary>
        public static string Assignment_DescriptionRequired {
            get {
                return ResourceManager.GetString("Assignment_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون تاريخ الاستحقاق في المستقبل.
        /// </summary>
        public static string Assignment_DueDateMustBeFuture {
            get {
                return ResourceManager.GetString("Assignment_DueDateMustBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاستحقاق مطلوب.
        /// </summary>
        public static string Assignment_DueDateRequired {
            get {
                return ResourceManager.GetString("Assignment_DueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكليف غير موجود.
        /// </summary>
        public static string Assignment_NotFound {
            get {
                return ResourceManager.GetString("Assignment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة يجب أن تكون صفراً أو أكثر.
        /// </summary>
        public static string Assignment_ScoreInvalid {
            get {
                return ResourceManager.GetString("Assignment_ScoreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف التسليم مطلوب.
        /// </summary>
        public static string Assignment_SubmissionIdRequired {
            get {
                return ResourceManager.GetString("Assignment_SubmissionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان التكليف يجب ألا يتجاوز 200 حرف.
        /// </summary>
        public static string Assignment_TitleMaxLength {
            get {
                return ResourceManager.GetString("Assignment_TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان التكليف مطلوب.
        /// </summary>
        public static string Assignment_TitleRequired {
            get {
                return ResourceManager.GetString("Assignment_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة الإجمالية يجب أن تكون أكبر من صفر.
        /// </summary>
        public static string Assignment_TotalScoreInvalid {
            get {
                return ResourceManager.GetString("Assignment_TotalScoreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب غير صالح.
        /// </summary>
        public static string BadRequestExceptionMessage {
            get {
                return ResourceManager.GetString("BadRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنت مسجل بالفعل في هذه المادة.
        /// </summary>
        public static string Course_AlreadyEnrolled {
            get {
                return ResourceManager.GetString("Course_AlreadyEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المادة يجب ألا يتجاوز 50 حرفاً.
        /// </summary>
        public static string Course_CodeMaxLength {
            get {
                return ResourceManager.GetString("Course_CodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المادة مطلوب.
        /// </summary>
        public static string Course_CodeRequired {
            get {
                return ResourceManager.GetString("Course_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون عدد الساعات المعتمدة بين 1 و 10.
        /// </summary>
        public static string Course_CreditHoursInvalid {
            get {
                return ResourceManager.GetString("Course_CreditHoursInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات المعتمدة مطلوب.
        /// </summary>
        public static string Course_CreditHoursRequired {
            get {
                return ResourceManager.GetString("Course_CreditHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على تسجيل لك في هذه المادة.
        /// </summary>
        public static string Course_EnrollmentNotFound {
            get {
                return ResourceManager.GetString("Course_EnrollmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المادة الدراسية مطلوب.
        /// </summary>
        public static string Course_IdRequired {
            get {
                return ResourceManager.GetString("Course_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة الدراسية غير موجودة.
        /// </summary>
        public static string Course_NotFound {
            get {
                return ResourceManager.GetString("Course_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الشعبة مطلوب.
        /// </summary>
        public static string Course_SectionIdRequired {
            get {
                return ResourceManager.GetString("Course_SectionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشعبة غير موجودة.
        /// </summary>
        public static string Course_SectionNotFound {
            get {
                return ResourceManager.GetString("Course_SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المادة يجب ألا يتجاوز 200 حرف.
        /// </summary>
        public static string Course_TitleMaxLength {
            get {
                return ResourceManager.GetString("Course_TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المادة مطلوب.
        /// </summary>
        public static string Course_TitleRequired {
            get {
                return ResourceManager.GetString("Course_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين المادة للقسم بنجاح.
        /// </summary>
        public static string CourseAssignedSuccessfully {
            get {
                return ResourceManager.GetString("CourseAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المادة مطلوب.
        /// </summary>
        public static string CourseIdRequired {
            get {
                return ResourceManager.GetString("CourseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المادة مطلوب من أجل حدث الامتحانات.
        /// </summary>
        public static string CourseIdRequiredForExamEvent {
            get {
                return ResourceManager.GetString("CourseIdRequiredForExamEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة غير موجودة.
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المادة من القسم بنجاح.
        /// </summary>
        public static string CourseRemovedSuccessfully {
            get {
                return ResourceManager.GetString("CourseRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار مادة واحدة على الأقل.
        /// </summary>
        public static string Courses_Required {
            get {
                return ResourceManager.GetString("Courses_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإنشاء بنجاح.
        /// </summary>
        public static string CreatedActionResultMessage {
            get {
                return ResourceManager.GetString("CreatedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeletedActionResultMessage {
            get {
                return ResourceManager.GetString("DeletedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الحذف.
        /// </summary>
        public static string DeletedFailed {
            get {
                return ResourceManager.GetString("DeletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود القسم يجب ألا يتجاوز 10 أحرف.
        /// </summary>
        public static string DepartmentCodeMaxLength {
            get {
                return ResourceManager.GetString("DepartmentCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود القسم مطلوب.
        /// </summary>
        public static string DepartmentCodeRequired {
            get {
                return ResourceManager.GetString("DepartmentCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود موجود بالفعل.
        /// </summary>
        public static string DepartmentCodeUnique {
            get {
                return ResourceManager.GetString("DepartmentCodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف القسم غير صحيح.
        /// </summary>
        public static string DepartmentIdNotFound {
            get {
                return ResourceManager.GetString("DepartmentIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف القسم مطلوب.
        /// </summary>
        public static string DepartmentIdRequired {
            get {
                return ResourceManager.GetString("DepartmentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى طول لاسم القسم يجب ألا يتجاوز 100 حرف.
        /// </summary>
        public static string DepartmentNameMaxLength {
            get {
                return ResourceManager.GetString("DepartmentNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القسم مطلوب.
        /// </summary>
        public static string DepartmentNameRequired {
            get {
                return ResourceManager.GetString("DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم غير موجود.
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف طلب الإرشاد الأكاديمي مطلوب.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل البريد الإلكتروني بنجاح.
        /// </summary>
        public static string EmailActivatedSuccessfully {
            get {
                return ResourceManager.GetString("EmailActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مفعل بالفعل.
        /// </summary>
        public static string EmailAlreadyActivated {
            get {
                return ResourceManager.GetString("EmailAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم موجود بالفعل.
        /// </summary>
        public static string EmailAlreadyExistedbefore {
            get {
                return ResourceManager.GetString("EmailAlreadyExistedbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني ينتهي بنطاق غير صالح.
        /// </summary>
        public static string EmailDomainInvalid {
            get {
                return ResourceManager.GetString("EmailDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صالح.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني لم يتم تفعيله بعد.
        /// </summary>
        public static string EmailNotActivated {
            get {
                return ResourceManager.GetString("EmailNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير موجود.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير موجود.
        /// </summary>
        public static string EmailNotFoundBefore {
            get {
                return ResourceManager.GetString("EmailNotFoundBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير محقق.
        /// </summary>
        public static string EmailUnVerified {
            get {
                return ResourceManager.GetString("EmailUnVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء يجب أن يكون أكبر من أو يساوي تاريخ بداية الحدث.
        /// </summary>
        public static string EndDateMustBeGreaterThanOrEqualEventDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanOrEqualEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية يجب أن يكون أكبر من تاريخ البداية.
        /// </summary>
        public static string EndDateMustBeGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية السنة الدراسية مطلوب.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الانتهاء يجب أن يكون بعد وقت البداية.
        /// </summary>
        public static string EndTimeMustBeGreaterThanStartTime {
            get {
                return ResourceManager.GetString("EndTimeMustBeGreaterThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت انتهاء الحدث مطلوب.
        /// </summary>
        public static string EndTimeRequired {
            get {
                return ResourceManager.GetString("EndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحدث مطلوب.
        /// </summary>
        public static string EventDateRequired {
            get {
                return ResourceManager.GetString("EventDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الحدث غير صالح.
        /// </summary>
        public static string EventIdNotValid {
            get {
                return ResourceManager.GetString("EventIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الحدث مطلوب.
        /// </summary>
        public static string EventIdRequired {
            get {
                return ResourceManager.GetString("EventIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث مطلوب.
        /// </summary>
        public static string EventNameRequired {
            get {
                return ResourceManager.GetString("EventNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية الامتحانات يجب أن يكون أكبر من تاريخ بدايتها.
        /// </summary>
        public static string ExamEndDateMustBeGreaterThanExamStartDate {
            get {
                return ResourceManager.GetString("ExamEndDateMustBeGreaterThanExamStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية الامتحانات يجب أن يكون أكبر من تاريخ بداية التسجيل.
        /// </summary>
        public static string ExamStartDateMustBeGreaterThanRegistrationStartDate {
            get {
                return ResourceManager.GetString("ExamStartDateMustBeGreaterThanRegistrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل إزالة الملف.
        /// </summary>
        public static string FaildToDeleted {
            get {
                return ResourceManager.GetString("FaildToDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل تسجيل هذا المستخدم.
        /// </summary>
        public static string FailedSignUp {
            get {
                return ResourceManager.GetString("FailedSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الملف مطلوب.
        /// </summary>
        public static string FileNameRequried {
            get {
                return ResourceManager.GetString("FileNameRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف غير موجود.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف ليس من الامتداد الصحيح أو غير موجود.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الملف غير صالح.
        /// </summary>
        public static string FilePalceNotValid {
            get {
                return ResourceManager.GetString("FilePalceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل رفع الملف.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل مطلوب.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس غير صالح.
        /// </summary>
        public static string GenderIsNotValid {
            get {
                return ResourceManager.GetString("GenderIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المستخدم للمعيد مطلوب.
        /// </summary>
        public static string InstructorUserIdRequired {
            get {
                return ResourceManager.GetString("InstructorUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع محتوى الملف غير صالح.
        /// </summary>
        public static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة النموذج غير صالحة.
        /// </summary>
        public static string InvalidModelStateExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidModelStateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidSignIn {
            get {
                return ResourceManager.GetString("InvalidSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التأكيد غير صحيح أو منتهي الصلاحية.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاضرة ممتلئة لـ {0}.
        /// </summary>
        public static string Lecture_Full {
            get {
                return ResourceManager.GetString("Lecture_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الحدث مطلوب.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث تجاوز الحد المسموح به.
        /// </summary>
        public static string MaxLengthOfEventNameExceededRequiredLength {
            get {
                return ResourceManager.GetString("MaxLengthOfEventNameExceededRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع الحدث تجاوز الحد المسموح به.
        /// </summary>
        public static string MaxLengthOfLocationExceededRequiredLength {
            get {
                return ResourceManager.GetString("MaxLengthOfLocationExceededRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي محجوز بالفعل.
        /// </summary>
        public static string NationalNumberExist {
            get {
                return ResourceManager.GetString("NationalNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي مطلوب.
        /// </summary>
        public static string NationalNumberRequired {
            get {
                return ResourceManager.GetString("NationalNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموارد المطلوب غير موجود.
        /// </summary>
        public static string NotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تنفيذ العملية بنجاح.
        /// </summary>
        public static string OkActionResultMessage {
            get {
                return ResourceManager.GetString("OkActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور لا يتطابق مع كلمة المرور.
        /// </summary>
        public static string PasswordConfirmNotEqual {
            get {
                return ResourceManager.GetString("PasswordConfirmNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب أن تكون 8 أحرف على الأقل.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مطلوبة.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل إعادة تعيين كلمة المرور.
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رمز إعادة التعيين.
        /// </summary>
        public static string PasswordResetMessage {
            get {
                return ResourceManager.GetString("PasswordResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق لإعادة تعيين كلمة المرور - رفيق.
        /// </summary>
        public static string PasswordResetSubject {
            get {
                return ResourceManager.GetString("PasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور بنجاح.
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;!DOCTYPE html&amp;gt;&amp;lt;html&amp;gt;&amp;lt;head&amp;gt;&amp;lt;meta charset=&quot;utf-8&quot; /&amp;gt;&amp;lt;title&amp;gt;إعادة تعيين كلمة المرور&amp;lt;/title&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body style=&quot;direction: rtl; text-align: right;&quot;&amp;gt;&amp;lt;h2&amp;gt;إعادة تعيين كلمة المرور&amp;lt;/h2&amp;gt;&amp;lt;p&amp;gt;مرحباً، @(Model.FullName) !&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;لقد طلبت إعادة تعيين كلمة المرور الخاصة بك لنظام رفيق. لإعادة تعيين كلمة المرور، يرجى استخدام رمز إعادة التعيين التالي:&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;رمز إعادة التعيين: &amp;lt;strong&amp;gt;@(Model.VerificationCode)&amp;lt;/strong&amp;gt;&amp;lt;/p&amp;gt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordResetTemplate {
            get {
                return ResourceManager.GetString("PasswordResetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور إما ضعيفة أو قد لا تستوفي المعايير المطلوبة.
        /// </summary>
        public static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صالح.
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف محجوز بالفعل.
        /// </summary>
        public static string PhoneNumberExist {
            get {
                return ResourceManager.GetString("PhoneNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف غير مدعوم.
        /// </summary>
        public static string PlaceNotSupported {
            get {
                return ResourceManager.GetString("PlaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الملف غير صالح.
        /// </summary>
        public static string PlaceNotValid {
            get {
                return ResourceManager.GetString("PlaceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور الأساسي يجب أن يكون صحيحاً.
        /// </summary>
        public static string PrimayRoleInvalid {
            get {
                return ResourceManager.GetString("PrimayRoleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تجاوز الحد المسموح به. يمكنك إنشاء 3 جداول فقط كل ساعة.
        /// </summary>
        public static string RateLimit_Exceeded {
            get {
                return ResourceManager.GetString("RateLimit_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء التكرار يجب أن يكون بعد تاريخ بداية الحدث.
        /// </summary>
        public static string RecurrenceEndDateMustBeAfterEventDate {
            get {
                return ResourceManager.GetString("RecurrenceEndDateMustBeAfterEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء التكرار مطلوب.
        /// </summary>
        public static string RecurrenceEndDateRequired {
            get {
                return ResourceManager.GetString("RecurrenceEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية التسجيل يجب أن يكون أكبر من تاريخ بداية التسجيل.
        /// </summary>
        public static string RegisterationEndDateMustBeGreaterThanRegistrationStartDate {
            get {
                return ResourceManager.GetString("RegisterationEndDateMustBeGreaterThanRegistrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية التسجيل يجب أن يكون أكبر من تاريخ بداية الترم الدراسي.
        /// </summary>
        public static string RegistrationStartDateMustBeGreaterThanAcademicTermStartDate {
            get {
                return ResourceManager.GetString("RegistrationStartDateMustBeGreaterThanAcademicTermStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ استحقاق التذكير مطلوب.
        /// </summary>
        public static string Reminder_DueDateRequired {
            get {
                return ResourceManager.GetString("Reminder_DueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف التذكير مطلوب.
        /// </summary>
        public static string Reminder_IdRequired {
            get {
                return ResourceManager.GetString("Reminder_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التذكير غير موجود.
        /// </summary>
        public static string Reminder_NotFound {
            get {
                return ResourceManager.GetString("Reminder_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان التذكير يجب ألا يتجاوز 200 حرف.
        /// </summary>
        public static string Reminder_TitleMaxLength {
            get {
                return ResourceManager.GetString("Reminder_TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان التذكير مطلوب.
        /// </summary>
        public static string Reminder_TitleRequired {
            get {
                return ResourceManager.GetString("Reminder_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الطلب مطلوب.
        /// </summary>
        public static string RequestIdRequired {
            get {
                return ResourceManager.GetString("RequestIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل إرسال طلب الإرشاد الأكاديمي.
        /// </summary>
        public static string RequestIsFailedToSend {
            get {
                return ResourceManager.GetString("RequestIsFailedToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل إرسال طلب الإرشاد الأكاديمي.
        /// </summary>
        public static string RequestIsFailedToSend1 {
            get {
                return ResourceManager.GetString("RequestIsFailedToSend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب الإرشاد الأكاديمي بنجاح.
        /// </summary>
        public static string RequestIsSentSuccessfully {
            get {
                return ResourceManager.GetString("RequestIsSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق غير صالح أو منتهي الصلاحية.
        /// </summary>
        public static string ResetTokenInvalid {
            get {
                return ResourceManager.GetString("ResetTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال بيانات المستخدم بنجاح إلى البريد الإلكتروني.
        /// </summary>
        public static string SendUserCredentialsMessage {
            get {
                return ResourceManager.GetString("SendUserCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات حسابك الجامعي - رفيق.
        /// </summary>
        public static string SendUserCredentialsSubject {
            get {
                return ResourceManager.GetString("SendUserCredentialsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;!DOCTYPE html&amp;gt;&amp;lt;html&amp;gt;&amp;lt;head&amp;gt;&amp;lt;meta charset=&quot;utf-8&quot; /&amp;gt;&amp;lt;title&amp;gt;بيانات حسابك الجامعي&amp;lt;/title&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body style=&quot;direction: rtl; text-align: right;&quot;&amp;gt;&amp;lt;h2&amp;gt;مرحباً بك في نظام رفيق الجامعي&amp;lt;/h2&amp;gt;&amp;lt;p&amp;gt;مرحباً، @(Model.FullName) !&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;تم إنشاء حسابك بنجاح. فيما يلي بيانات تسجيل الدخول الخاصة بك:&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;البريد الجامعي: &amp;lt;strong&amp;gt;@(Model.Email)&amp;lt;/strong&amp;gt;&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;كلمة المرور المؤقتة: &amp;lt;strong&amp;gt;@(Model.Password)&amp;lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendUserCredentialsTemplate {
            get {
                return ResourceManager.GetString("SendUserCredentialsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلة الجلسة يجب أن تكون أكبر من 0 دقيقة.
        /// </summary>
        public static string SessionTimeoutInvalid {
            get {
                return ResourceManager.GetString("SessionTimeoutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية السنة الدراسية مطلوب.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت بدء الحدث مطلوب.
        /// </summary>
        public static string StartTimeRequired {
            get {
                return ResourceManager.GetString("StartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الطالب مطلوب.
        /// </summary>
        public static string StudentIdRequired {
            get {
                return ResourceManager.GetString("StudentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي للطالب غير موجود.
        /// </summary>
        public static string StudentProfileNotFound {
            get {
                return ResourceManager.GetString("StudentProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة معرفات الطلاب غير موجودة.
        /// </summary>
        public static string StudentsNotFound {
            get {
                return ResourceManager.GetString("StudentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المستخدم المستهدف مطلوب.
        /// </summary>
        public static string TargetUserIdRequired {
            get {
                return ResourceManager.GetString("TargetUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات طلب الجدول مطلوبة.
        /// </summary>
        public static string TimetableRequest_Required {
            get {
                return ResourceManager.GetString("TimetableRequest_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان طلب الإرشاد الأكاديمي مطلوب.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوكن منتهي الصلاحية.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوكن غير موجود.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوكن غير صالح.
        /// </summary>
        public static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوكن مطلوب.
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق الثنائي مطلوب.
        /// </summary>
        public static string TwoFactorRequired {
            get {
                return ResourceManager.GetString("TwoFactorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول غير مصرح به.
        /// </summary>
        public static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل توليد كود جامعي جديد.
        /// </summary>
        public static string UniversityCodeMultipleAttemps {
            get {
                return ResourceManager.GetString("UniversityCodeMultipleAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل توليد بريد جامعي جديد.
        /// </summary>
        public static string UniversityEmailMultipleAttemps {
            get {
                return ResourceManager.GetString("UniversityEmailMultipleAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير معروف.
        /// </summary>
        public static string UnknownExceptionMessage {
            get {
                return ResourceManager.GetString("UnknownExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل التحديث.
        /// </summary>
        public static string UpdatedFailed {
            get {
                return ResourceManager.GetString("UpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بنجاح.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين المستخدم للقسم بنجاح.
        /// </summary>
        public static string UserAssignedSuccessfully {
            get {
                return ResourceManager.GetString("UserAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المستخدم محجوز بالفعل.
        /// </summary>
        public static string UserCodeExist {
            get {
                return ResourceManager.GetString("UserCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المستخدم مغلق.
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم هذا لا يمكن تعيينه لقسم.
        /// </summary>
        public static string UserNotEligibleForDepartment {
            get {
                return ResourceManager.GetString("UserNotEligibleForDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير موجود.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير معين في أي قسم.
        /// </summary>
        public static string UserNotInDepartment {
            get {
                return ResourceManager.GetString("UserNotInDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المستخدم من القسم بنجاح.
        /// </summary>
        public static string UserRemovedSuccessfully {
            get {
                return ResourceManager.GetString("UserRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على دور أكاديمي (طالب/دكتور/محاضر) لهذا المستخدم.
        /// </summary>
        public static string UserRoleNotFound {
            get {
                return ResourceManager.GetString("UserRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث استثناء في التحقق.
        /// </summary>
        public static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب الإرشاد غير موجود أو حالة الطلب ليست قيد الانتظار أو أن الطالب ليس تحت إرشادك.
        /// </summary>
        public static string YouAreNotAdvisorOfThatStudent {
            get {
                return ResourceManager.GetString("YouAreNotAdvisorOfThatStudent", resourceCulture);
            }
        }
    }
}
