//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rafeek.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rafeek.Application.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted successfully..
        /// </summary>
        public static string AcceptedActionResultMessage {
            get {
                return ResourceManager.GetString("AcceptedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to added a new record..
        /// </summary>
        public static string AddedFailed {
            get {
                return ResourceManager.GetString("AddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is added succefully..
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All additional roles must be a valid role type..
        /// </summary>
        public static string AdditionalRolesInvalid {
            get {
                return ResourceManager.GetString("AdditionalRolesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        public static string BadRequestExceptionMessage {
            get {
                return ResourceManager.GetString("BadRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Id required for exam event..
        /// </summary>
        public static string CourseIdRequiredForExamEvent {
            get {
                return ResourceManager.GetString("CourseIdRequiredForExamEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully..
        /// </summary>
        public static string CreatedActionResultMessage {
            get {
                return ResourceManager.GetString("CreatedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        public static string DeletedActionResultMessage {
            get {
                return ResourceManager.GetString("DeletedActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deleted a new record..
        /// </summary>
        public static string DeletedFailed {
            get {
                return ResourceManager.GetString("DeletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is deleted succefully..
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is activated successfully..
        /// </summary>
        public static string EmailActivatedSuccessfully {
            get {
                return ResourceManager.GetString("EmailActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already activated..
        /// </summary>
        public static string EmailAlreadyActivated {
            get {
                return ResourceManager.GetString("EmailAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists before..
        /// </summary>
        public static string EmailAlreadyExistedbefore {
            get {
                return ResourceManager.GetString("EmailAlreadyExistedbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ends with invalid domain..
        /// </summary>
        public static string EmailDomainInvalid {
            get {
                return ResourceManager.GetString("EmailDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not activated yet..
        /// </summary>
        public static string EmailNotActivated {
            get {
                return ResourceManager.GetString("EmailNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not found..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is not found before..
        /// </summary>
        public static string EmailNotFoundBefore {
            get {
                return ResourceManager.GetString("EmailNotFoundBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is unverified..
        /// </summary>
        public static string EmailUnVerified {
            get {
                return ResourceManager.GetString("EmailUnVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater that or equal event date..
        /// </summary>
        public static string EndDateMustBeGreaterThanOrEqualEventDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanOrEqualEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be greater that a start time..
        /// </summary>
        public static string EndTimeMustBeGreaterThanStartTime {
            get {
                return ResourceManager.GetString("EndTimeMustBeGreaterThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time is required..
        /// </summary>
        public static string EndTimeRequired {
            get {
                return ResourceManager.GetString("EndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date is required..
        /// </summary>
        public static string EventDateRequired {
            get {
                return ResourceManager.GetString("EventDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id is not valid..
        /// </summary>
        public static string EventIdNotValid {
            get {
                return ResourceManager.GetString("EventIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id Required..
        /// </summary>
        public static string EventIdRequired {
            get {
                return ResourceManager.GetString("EventIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required..
        /// </summary>
        public static string EventNameRequired {
            get {
                return ResourceManager.GetString("EventNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Deletion Failed..
        /// </summary>
        public static string FaildToDeleted {
            get {
                return ResourceManager.GetString("FaildToDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign up that user..
        /// </summary>
        public static string FailedSignUp {
            get {
                return ResourceManager.GetString("FailedSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Requried.
        /// </summary>
        public static string FileNameRequried {
            get {
                return ResourceManager.GetString("FileNameRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has incorrect extension or does not exist.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of file is not valid..
        /// </summary>
        public static string FilePalceNotValid {
            get {
                return ResourceManager.GetString("FilePalceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Failed..
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname required..
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender..
        /// </summary>
        public static string GenderIsNotValid {
            get {
                return ResourceManager.GetString("GenderIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type is not valid..
        /// </summary>
        public static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model state..
        /// </summary>
        public static string InvalidModelStateExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidModelStateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password!..
        /// </summary>
        public static string InvalidSignIn {
            get {
                return ResourceManager.GetString("InvalidSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Invalid or expiration..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is exceeded the required length..
        /// </summary>
        public static string MaxLengthOfEventNameExceededRequiredLength {
            get {
                return ResourceManager.GetString("MaxLengthOfEventNameExceededRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of event must not exceeded the required length..
        /// </summary>
        public static string MaxLengthOfLocationExceededRequiredLength {
            get {
                return ResourceManager.GetString("MaxLengthOfLocationExceededRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Number is already taken..
        /// </summary>
        public static string NationalNumberExist {
            get {
                return ResourceManager.GetString("NationalNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National number required..
        /// </summary>
        public static string NationalNumberRequired {
            get {
                return ResourceManager.GetString("NationalNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string NotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfully..
        /// </summary>
        public static string OkActionResultMessage {
            get {
                return ResourceManager.GetString("OkActionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation value not equals to password value..
        /// </summary>
        public static string PasswordConfirmNotEqual {
            get {
                return ResourceManager.GetString("PasswordConfirmNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length must be 8 characters..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Code Sent..
        /// </summary>
        public static string PasswordResetMessage {
            get {
                return ResourceManager.GetString("PasswordResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Code for Rafeek..
        /// </summary>
        public static string PasswordResetSubject {
            get {
                return ResourceManager.GetString("PasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;title&gt;Password Reset&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h2&gt;Password Reset&lt;/h2&gt;&lt;p&gt;Hello, @(Model.FullName) !&lt;/p&gt;&lt;p&gt;You have requested to reset your password for Rafeek. To reset your password, please use the following reset code:&lt;/p&gt;&lt;p&gt;Reset Code: &lt;strong&gt;@(Model.VerificationCode)&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;If you didn&apos;t request this password reset, you can safely ignore this email.&lt;/p&gt;&lt;p&gt;Regards,&lt;/p&gt;&lt;p&gt;The Rafeek Team&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string PasswordResetTemplate {
            get {
                return ResourceManager.GetString("PasswordResetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may be weak. Or it doesn&apos;t accepted cause of criteria..
        /// </summary>
        public static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is already taken..
        /// </summary>
        public static string PhoneNumberExist {
            get {
                return ResourceManager.GetString("PhoneNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number required..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place file Not Supported..
        /// </summary>
        public static string PlaceNotSupported {
            get {
                return ResourceManager.GetString("PlaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of file is not valid..
        /// </summary>
        public static string PlaceNotValid {
            get {
                return ResourceManager.GetString("PlaceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary role must be a valid role type..
        /// </summary>
        public static string PrimayRoleInvalid {
            get {
                return ResourceManager.GetString("PrimayRoleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence end date must be after event date..
        /// </summary>
        public static string RecurrenceEndDateMustBeAfterEventDate {
            get {
                return ResourceManager.GetString("RecurrenceEndDateMustBeAfterEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence end date is required..
        /// </summary>
        public static string RecurrenceEndDateRequired {
            get {
                return ResourceManager.GetString("RecurrenceEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired password reset token..
        /// </summary>
        public static string ResetTokenInvalid {
            get {
                return ResourceManager.GetString("ResetTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User credentials sent successfully to email..
        /// </summary>
        public static string SendUserCredentialsMessage {
            get {
                return ResourceManager.GetString("SendUserCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your University Account Credentials - Rafeek.
        /// </summary>
        public static string SendUserCredentialsSubject {
            get {
                return ResourceManager.GetString("SendUserCredentialsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;title&gt;Your University Credentials&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h2&gt;Welcome to Rafeek University System&lt;/h2&gt;&lt;p&gt;Hello, @(Model.FullName) !&lt;/p&gt;&lt;p&gt;Your account has been successfully created. Below are your login credentials:&lt;/p&gt;&lt;p&gt;University Email: &lt;strong&gt;@(Model.Email)&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;Temporary Password: &lt;strong&gt;@(Model.Password)&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Important:&lt;/strong&gt; For security reasons, please change your password after your first login.&lt;/p&gt;&lt;p&gt;You can now acces [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendUserCredentialsTemplate {
            get {
                return ResourceManager.GetString("SendUserCredentialsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is required..
        /// </summary>
        public static string StartTimeRequired {
            get {
                return ResourceManager.GetString("StartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted user Id is required..
        /// </summary>
        public static string TargetUserIdRequired {
            get {
                return ResourceManager.GetString("TargetUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now, Token is expired..
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not found..
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token..
        /// </summary>
        public static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required..
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate unique university code after multiple attempts..
        /// </summary>
        public static string UniversityCodeMultipleAttemps {
            get {
                return ResourceManager.GetString("UniversityCodeMultipleAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate unique university email after multiple attempts..
        /// </summary>
        public static string UniversityEmailMultipleAttemps {
            get {
                return ResourceManager.GetString("UniversityEmailMultipleAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownExceptionMessage {
            get {
                return ResourceManager.GetString("UnknownExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to updated a new record..
        /// </summary>
        public static string UpdatedFailed {
            get {
                return ResourceManager.GetString("UpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is updated succefully..
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code is already taken..
        /// </summary>
        public static string UserCodeExist {
            get {
                return ResourceManager.GetString("UserCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked out..
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation exception occurred..
        /// </summary>
        public static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
    }
}
